[build]
publish = "public"
command = "bin/install"

[[redirects]]
from = "/writing/rss.xml"
to = "/posts/rss.xml"

[[redirects]]
from = "/posts/rss.xml"
to = "/rss.xml"

[[redirects]]
from = "/writing/"
to = "/posts/"

[[redirects]]
from = "/writing"
to = "/posts"
